name: Run Capella Export

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run export
        run: |
          docker run --rm \
            -e CB_HOST="${{ secrets.CB_HOST }}" \
            -e CB_USER="${{ secrets.CB_USER }}" \
            -e CB_PASSWORD="${{ secrets.CB_PASSWORD }}" \
            -e CB_BUCKET="${{ secrets.CB_BUCKET }}" \
            -e R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}" \
            -e R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}" \
            -e R2_ENDPOINT="${{ secrets.R2_ENDPOINT }}" \
            -e R2_BUCKET="${{ secrets.R2_BUCKET }}" \
            -e EXPORT_DIR="/tmp/export" \
            -e EXPORT_FILE="raw_data.json" \
            -e ARCHIVE_NAME="couchbase_backup_bl.tar.gz" \
            -e SCOPE_FIELD="${{ secrets.CB_SCOPE }}" \
            ghcr.io/sdad454f/capella-backup:latest
